services:
  server:
    build:
      context: ./server
    container_name: p2p-server
    ports:
      - "1234:1234"
    networks:
      p2pnet:
        ipv4_address: 172.28.0.10

  client1:
    build:
      context: ./client1
    container_name: p2p-client1
    depends_on:
      - server
    networks:
      p2pnet:
        ipv4_address: 172.28.0.11

  client2:
    build:
      context: ./client2
    container_name: p2p-client2
    depends_on:
      - server
    networks:
      p2pnet:
        ipv4_address: 172.28.0.12

networks:
  p2pnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
